#!/bin/sh
#
# Date: 2024-23-05
# By  : Kevin L. Esteb
#
# Create a "release" in the repository.
#
TEST="false"
VERSION=
MESSAGE=
#
usage() {
cat << EOF

usage $0 <version> <message>
 
This script creates a release in the repository.
 
ARGUMENTS
  <version>    The version of the release.
  <message>    The message for the release. This should be quoted.

OPTIONS
  -h    Show this message.
  -t    Test. Show what would be done.

EOF
}
#
while getopts "ht" OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
    t)
      TEST="true"
      ;;
    ?)
      usage
      exit 1
      ;;
  esac
done
#
if [ "$OPTIND" -gt "$#" ]; then
  usage
  exit 2
fi
#
shiftcount=`expr $OPTIND - 1`
shift $shiftcount
VERSION=$1
MESSAGE=$2
#
if [ "$TEST" = "true" ]; then
    echo "git tag -a $VERSION -m \"$MESSAGE\"\n"
else
    git tag -a $VERSION -m "$MESSAGE"
fi
#
